version: "3.9"
services:
        python:
                build: .
                restart: "on-failure"
        crate:
                image: 'crate'
                ports:
                        - "4200:4200"
                restart: "on-failure"
