version: "3.9"
services:
        clientapp:
                build: .
                volumes:
                        - python_as:/app
        crate:
                image: crate:latest
                ports:
                        - "4200:4200"
                volumes:
                        - crate_as:/data
                command:
                        [ "crate","-Cnetwork.host=_site_",
                                   "-Cnode.data=true",
                                   "-Cdiscovery.type=single-node",]
                environment:
                        - CRATE_HEAP_SIZE=2g

volumes:
        python_as:
        crate_as:
