version: "3.9"
services:
        clientapp:
                build: 
                        context: .
                        dockerfile: Dockerfile
        crate:
                image: 'crate'
                ports:
                        - "4200:4200"
