version: "3.9"
services:
        clientapp:
                build: .
                volumes:
                        - python_as:/app
        crate:
                image: 'crate'
                ports:
                        - "4200:4200"
                volumes:
                        - crate_as:/data
                command:
                        [ "crate","-Cnetwork.host=_site_",
                                   "-Cnode.data=true",]
                environment:
                        - CRATE_HEAP_SIZE=1G

volumes:
        python_as:
        crate_as:
